#!/usr/bin/env bun
// Build-time generator: reads real source (module manifests, permit-node
// vocabulary, the RPC contract, env var readers, and command decorators) and
// writes typed data modules under src/generated/ for the reference pages to
// import. Gitignored, regenerated on every `bun run generate` (also run by
// `dev`/`build`) — never hand-edit anything under src/generated/.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DOCS_ROOT = path.resolve(fileURLToPath(new URL("../", import.meta.url)));
const REPO_ROOT = path.resolve(DOCS_ROOT, "../../");
const OUT_DIR = path.join(DOCS_ROOT, "src/generated");

async function writeGenerated(file: string, content: string): Promise<void> {
  await fs.mkdir(OUT_DIR, { recursive: true });
  const header = `// GENERATED by apps/docs/scripts/generate-content.ts — do not edit by hand.\n`;
  await fs.writeFile(path.join(OUT_DIR, file), header + content, "utf8");
}

const MODULE_NAMES = [
  "afk", "core", "dashboard", "economy", "filter", "logging", "mod",
  "reactionroles", "security", "tempvc", "utility", "welcome",
] as const;

interface Manifest {
  name: string;
  displayName: string;
  emoji: string;
  description: string;
  short: string;
  endUserDataStatement?: string;
  disableable: boolean;
  category: string;
  configFields: {
    key: string;
    type: string;
    label: string;
    description: string;
    group?: string;
    default?: unknown;
  }[];
}

async function loadManifests(): Promise<Manifest[]> {
  const manifests: Manifest[] = [];
  for (const name of MODULE_NAMES) {
    const p = path.join(REPO_ROOT, "packages/core/src/modules", name, "manifest.json");
    const raw = await fs.readFile(p, "utf8");
    manifests.push(JSON.parse(raw) as Manifest);
  }
  return manifests;
}

// --- 1. Modules -------------------------------------------------------------

async function generateModules(manifests: Manifest[]): Promise<void> {
  const rows = manifests.map((m) => ({
    name: m.name,
    displayName: m.displayName,
    emoji: m.emoji,
    description: m.description,
    short: m.short,
    category: m.category,
    disableable: m.disableable,
    configFieldCount: m.configFields.length,
  }));
  await writeGenerated(
    "modules.ts",
    `export interface ModuleSummary {
  name: string;
  displayName: string;
  emoji: string;
  description: string;
  short: string;
  category: string;
  disableable: boolean;
  configFieldCount: number;
}

export const modules: ModuleSummary[] = ${JSON.stringify(rows, null, 2)};
`,
  );
}

// --- 2. Data and privacy -----------------------------------------------------

async function generateDataPrivacy(manifests: Manifest[]): Promise<void> {
  const rows = manifests.map((m) => ({
    name: m.name,
    displayName: m.displayName,
    statement: m.endUserDataStatement ?? null,
  }));
  await writeGenerated(
    "data-privacy.ts",
    `export interface DataPrivacyRow {
  name: string;
  displayName: string;
  /** null when the module's manifest.json declares no endUserDataStatement. */
  statement: string | null;
}

export const dataPrivacyRows: DataPrivacyRow[] = ${JSON.stringify(rows, null, 2)};
`,
  );
}

// --- 3. Permit nodes ----------------------------------------------------------

async function generatePermits(): Promise<void> {
  const mod = await import(
    path.join(REPO_ROOT, "packages/contracts/src/permit-nodes.ts")
  );
  const groups = mod.KnownPermitNodeGroups as { prefix: string; nodes: string[] }[];
  await writeGenerated(
    "permits.ts",
    `export interface PermitNodeGroup {
  prefix: string;
  nodes: string[];
}

export const permitNodeGroups: PermitNodeGroup[] = ${JSON.stringify(groups, null, 2)};

export const permitNodeCount: number = permitNodeGroups.reduce(
  (total, group) => total + group.nodes.length,
  0,
);
`,
  );
}

// --- 4. Environment variables --------------------------------------------------
// env.ts and dashboard/src/lib/env.ts have no single schema object to import —
// they're a bag of functions/getters reading process.env["KEY"] ad hoc. Real
// generation of names is possible (regex-scan for the literal reads); the
// required/default/description columns cannot be extracted from source
// without a lot of bespoke parsing for marginal gain, so they stay a
// hand-maintained lookup here, and the generator fails the build if a scanned
// key has no lookup entry or a lookup entry no longer matches a scanned key —
// the drift check the old configuration/page.tsx never had.

interface EnvMeta {
  required: string;
  fallback: string;
  about: string;
}

const workerMeta: Record<string, EnvMeta> = {
  BOT_TOKEN: { required: "yes", fallback: "—", about: "Discord bot token. The worker refuses to start without it." },
  TOTAL_SHARDS: { required: "no", fallback: "auto", about: "Shard count for the ShardingManager, or auto to let Discord decide." },
  SHARD_LIST: { required: "no", fallback: "auto", about: "Comma-separated shard ids this deployment owns, or auto." },
  POSTGRES_URL: { required: "yes", fallback: "—", about: "Primary Postgres connection string (point it at PgBouncer in Compose)." },
  POSTGRES_REPLICA_URL: { required: "no", fallback: "—", about: "Optional read-replica connection string." },
  POSTGRES_APP_NAME: { required: "no", fallback: "lumi-worker-<shards>", about: "application_name reported to Postgres per process." },
  POSTGRES_POOL_MAX: { required: "no", fallback: "derived", about: "Explicit per-process pool size. Wins over the budget below." },
  POSTGRES_POOL_TOTAL: { required: "no", fallback: "80", about: "Fleet-wide connection budget, divided across shards so scaling out never exhausts max_connections." },
  DIRECT_POSTGRES_URL: { required: "no", fallback: "—", about: "Direct Postgres URL used by migrations, bypassing PgBouncer." },
  REDIS_HOST: { required: "no", fallback: "127.0.0.1", about: "Standalone/sentinel Redis host." },
  REDIS_PORT: { required: "no", fallback: "6379", about: "Standalone/sentinel Redis port." },
  REDIS_PASSWORD: { required: "no", fallback: "—", about: "Redis password." },
  REDIS_CACHE_DB: { required: "no", fallback: "—", about: "Logical database index for cache data." },
  REDIS_TASK_DB: { required: "no", fallback: "—", about: "Logical database index for scheduled-task data." },
  REDIS_SENTINELS: { required: "no", fallback: "—", about: "Sentinel addresses when running Redis in sentinel mode." },
  REDIS_SENTINEL_NAME: { required: "no", fallback: "—", about: "Sentinel master name." },
  REDIS_SENTINEL_PASSWORD: { required: "no", fallback: "—", about: "Sentinel password." },
  REDIS_CLUSTER_NODES: { required: "no", fallback: "—", about: "Comma-separated host:port list enabling cluster mode." },
  REDIS_CLUSTER_SCALE_READS: { required: "no", fallback: "master", about: "Read scaling policy: master, slave, or all." },
  REDIS_CLUSTER_SLOTS_REFRESH_TIMEOUT_MS: { required: "no", fallback: "2000", about: "Slot-refresh timeout for the cluster client." },
  RPC_HTTP_HOST: { required: "no", fallback: "127.0.0.1", about: "Bind for the worker RPC/metrics surface. Widened to 0.0.0.0 only on the container the dashboard calls." },
  RPC_HTTP_PORT: { required: "no", fallback: "8091", about: "Port for the worker RPC/metrics surface." },
  RPC_INTERNAL_TOKEN: { required: "yes", fallback: "—", about: "Shared secret authenticating dashboard-to-worker RPC. Unset is a hard failure." },
  OWNER_IDS: { required: "no", fallback: "—", about: "Extra bot-owner ids recognized by the permit resolver (the Discord application owner is always an owner)." },
  LUMI_CONSUMER_ID: { required: "no", fallback: "hostname / pid", about: "Stable consumer identity for stream processing." },
  CLUSTER_NAME: { required: "no", fallback: "default", about: "Namespaces shard telemetry per replica for the fleet view." },
  LUMI_DEV_PATHS: { required: "no", fallback: "—", about: "Colon/comma-separated extra module directories for local add-on development. Never set in production." },
  DISCORD_PROXY_URL: { required: "no", fallback: "—", about: "Shared outbound REST proxy root (nirn-proxy). Unset means direct Discord API calls." },
  DASHBOARD_PUBLIC_URL: { required: "no", fallback: "—", about: "Public dashboard origin used to build appeal links. Unset skips appeal links." },
  NODE_ENV: { required: "no", fallback: "development", about: "Runtime environment flag." },
  SHARD_COUNT: { required: "no", fallback: "1", about: "Injected by the ShardingManager; do not set yourself." },
  SHARDS: { required: "no", fallback: "—", about: "Injected by the ShardingManager as this process's shard id list; do not set yourself." },
  SHARDING_MANAGER: { required: "no", fallback: "—", about: "Injected by the ShardingManager to mark a child process; do not set yourself." },
  HOSTNAME: { required: "no", fallback: "container hostname", about: "Used as a consumer-id fallback; normally set by the container runtime, not you." },
  CACHE_MESSAGE_LIMIT: { required: "no", fallback: "50", about: "Max cached messages per channel." },
  CACHE_MEMBER_LIMIT: { required: "no", fallback: "50", about: "Max cached guild members per guild." },
  CACHE_THREAD_LIMIT: { required: "no", fallback: "25", about: "Max cached threads per channel." },
  CACHE_USER_LIMIT: { required: "no", fallback: "200", about: "Max cached users." },
  SWEEPER_MESSAGES_INTERVAL: { required: "no", fallback: "300", about: "Seconds between message-cache sweeps." },
  SWEEPER_MESSAGES_LIFETIME: { required: "no", fallback: "600", about: "Seconds a cached message survives before being swept." },
  SWEEPER_MEMBERS_INTERVAL: { required: "no", fallback: "1800", about: "Seconds between guild-member-cache sweeps." },
  SWEEPER_MEMBERS_LIFETIME: { required: "no", fallback: "1800", about: "Seconds a cached non-self member survives before being swept." },
  DEFAULT_PREFIX: { required: "no", fallback: ",", about: "Legacy text-command prefix." },
  SERVICE_NAME: { required: "no", fallback: "lumi", about: "Service name reported to the logger and observability exporters." },
};

const dashboardMeta: Record<string, EnvMeta> = {
  DASHBOARD_HOST: { required: "no", fallback: "0.0.0.0", about: "Interface the dashboard binds." },
  DASHBOARD_PORT: { required: "no", fallback: "8080", about: "Port the dashboard listens on." },
  DASHBOARD_SESSION_SECRET: { required: "yes", fallback: "—", about: "NextAuth session JWT encryption secret." },
  DISCORD_OAUTH2_CLIENT_ID: { required: "yes", fallback: "—", about: "Discord application client id." },
  DISCORD_OAUTH2_CLIENT_SECRET: { required: "yes", fallback: "—", about: "Discord application client secret." },
  RPC_HTTP_URL: { required: "yes", fallback: "—", about: "Base URL of the worker RPC server, e.g. http://worker:8091." },
  RPC_INTERNAL_TOKEN: { required: "no", fallback: "\"\"", about: "Shared secret sent as the RPC bearer token. Must match the worker's value; optional only so a local dev worker without the token still works." },
  TRUSTED_PROXY_HOPS: { required: "no", fallback: "1", about: "Number of trusted reverse-proxy hops when reading the client IP." },
  CLIENT_IP_HEADER: { required: "no", fallback: "—", about: "Header to trust for the client IP behind a reverse proxy." },
  AUTH_URL: { required: "proxy only", fallback: "—", about: "Externally visible origin when a reverse proxy rewrites Host." },
  NEXT_PHASE: { required: "no", fallback: "—", about: "Set by Next.js itself during `next build`; not something you set." },
  NODE_ENV: { required: "no", fallback: "development", about: "Runtime environment flag." },
};

/**
 * Regex-scan for every env var literal actually read in a file — direct
 * `process.env["KEY"]` reads, plus this file's own thin parser helpers
 * (`envParseString`/`envParseInteger`/`envStr`/`envInt`), which take the key
 * as their first string-literal argument rather than indexing `process.env`
 * directly.
 */
async function scanEnvKeys(file: string): Promise<Set<string>> {
  const src = await fs.readFile(file, "utf8");
  const keys = new Set<string>();
  for (const m of src.matchAll(/process\.env\[["']([A-Z0-9_]+)["']\]/g)) {
    keys.add(m[1]!);
  }
  for (const m of src.matchAll(/process\.env\.([A-Z0-9_]+)\b/g)) {
    keys.add(m[1]!);
  }
  for (const m of src.matchAll(/\benv(?:ParseString|ParseInteger|Str|Int)\(\s*["']([A-Z0-9_]+)["']/g)) {
    keys.add(m[1]!);
  }
  return keys;
}

function toRows(meta: Record<string, EnvMeta>) {
  return Object.entries(meta).map(([name, m]) => ({ name, ...m }));
}

// Worker env vars aren't confined to env.ts — the Redis client, RPC HTTP
// server, and permit resolver each read a few of their own directly.
const WORKER_ENV_FILES = [
  "packages/core/src/lib/env.ts",
  "packages/core/src/lib/database/redis.ts",
  "packages/core/src/lib/rpc/http-server.ts",
  "packages/core/src/lib/permissions/PermitResolver.ts",
  "packages/core/src/lib/client/client-options.ts",
  "prisma.config.ts",
];

// AUTH_URL is consumed by NextAuth's own convention-based env lookup, never
// read directly in application code, so it can't be scanned for.
const DASHBOARD_ENV_SCAN_EXCEPTIONS = new Set(["AUTH_URL"]);

async function generateEnvVars(): Promise<void> {
  const workerScanned = new Set<string>();
  for (const file of WORKER_ENV_FILES) {
    for (const key of await scanEnvKeys(path.join(REPO_ROOT, file))) workerScanned.add(key);
  }
  const dashboardScanned = await scanEnvKeys(
    path.join(REPO_ROOT, "apps/dashboard/src/lib/env.ts"),
  );

  const problems: string[] = [];
  for (const key of workerScanned) {
    if (!(key in workerMeta)) problems.push(`a worker env source file reads ${key}, which has no docs metadata`);
  }
  for (const key of Object.keys(workerMeta)) {
    if (!workerScanned.has(key)) problems.push(`docs metadata for ${key} has no matching process.env read in ${WORKER_ENV_FILES.join(", ")}`);
  }
  for (const key of dashboardScanned) {
    if (!(key in dashboardMeta)) problems.push(`apps/dashboard/src/lib/env.ts reads ${key}, which has no docs metadata`);
  }
  for (const key of Object.keys(dashboardMeta)) {
    if (DASHBOARD_ENV_SCAN_EXCEPTIONS.has(key)) continue;
    if (!dashboardScanned.has(key)) problems.push(`docs metadata for ${key} has no matching process.env read in apps/dashboard/src/lib/env.ts`);
  }
  if (problems.length > 0) {
    throw new Error(
      `[generate-content] Environment variable reference drifted from source:\n  ${problems.join("\n  ")}`,
    );
  }

  // Compose-only and observability vars are consumed by docker-compose.yml /
  // packages/observability rather than a single scannable TS file; kept as a
  // plain hand-maintained table with no automated drift check.
  const observabilityRows: (EnvMeta & { name: string })[] = [
    { name: "OTEL_ENABLED", required: "no", fallback: "true", about: "Enable OpenTelemetry tracing." },
    { name: "OTEL_EXPORTER_OTLP_ENDPOINT", required: "no", fallback: "collector:4318", about: "OTLP endpoint traces are exported to." },
    { name: "OTEL_TRACES_SAMPLE_RATIO", required: "no", fallback: "1", about: "Trace sampling ratio." },
    { name: "OTEL_DIAG", required: "no", fallback: "—", about: "OpenTelemetry diagnostics flag." },
    { name: "METRICS_ENABLED", required: "no", fallback: "true", about: "Serve /healthz, /readyz, and /metrics." },
    { name: "METRICS_HOST", required: "no", fallback: "—", about: "Bind for the telemetry server." },
    { name: "METRICS_PORT", required: "no", fallback: "9090", about: "Port for the telemetry server." },
    { name: "LOG_FORMAT", required: "no", fallback: "json", about: "Log encoding: json in Compose, pretty in the dev container." },
    { name: "LOG_LEVEL", required: "no", fallback: "info", about: "Minimum log level." },
  ];
  const composeRows: (EnvMeta & { name: string })[] = [
    { name: "POSTGRES_USER", required: "no", fallback: "lumi", about: "Postgres superuser name created at init." },
    { name: "POSTGRES_PASSWORD", required: "no", fallback: "lumi", about: "Postgres password. Change it in any shared deployment." },
    { name: "GRAFANA_USER", required: "no", fallback: "admin", about: "Grafana admin username (observability profile)." },
    { name: "GRAFANA_PASSWORD", required: "yes*", fallback: "—", about: "*Required only under the observability profile. No default on purpose." },
    { name: "NIRN_LOG_LEVEL", required: "no", fallback: "info", about: "Log level for the nirn outbound proxy (scale profile)." },
  ];

  await writeGenerated(
    "env-vars.ts",
    `export interface EnvRow {
  name: string;
  required: string;
  fallback: string;
  about: string;
}

export const workerEnvVars: EnvRow[] = ${JSON.stringify(toRows(workerMeta), null, 2)};

export const dashboardEnvVars: EnvRow[] = ${JSON.stringify(toRows(dashboardMeta), null, 2)};

export const observabilityEnvVars: EnvRow[] = ${JSON.stringify(observabilityRows, null, 2)};

export const composeEnvVars: EnvRow[] = ${JSON.stringify(composeRows, null, 2)};
`,
  );
}

// --- 5. RPC actions -----------------------------------------------------------
// The action -> payload-type mapping is mechanical from RpcRequestPayloads;
// one-line summaries can't be derived from a type name, so they stay a
// hand-maintained lookup that the generator checks for drift both ways.

const rpcSummaries: Record<string, string> = {
  "global.gdpr.delete": "Erase a user's data.",
  "global.gdpr.export": "Export a user's data, keyed by module.",
  "downloader.repo.add": "Register a module repo.",
  "downloader.repo.list": "List registered repos.",
  "downloader.repo.modules": "List modules a repo offers.",
  "downloader.module.install": "Install a module from a repo.",
  "downloader.module.uninstall": "Uninstall a module.",
  "downloader.module.rollback": "Roll a module back to a revision.",
  "guild.dashboard.get": "Full dashboard view for a guild.",
  "guild.summaries.list": "Decorative guild rows (icon, banner, member count).",
  "guild.module.toggle": "Enable or disable a module for a guild.",
  "guild.config.set": "Write one config key (omitted value deletes it).",
  "guild.config.setMany": "Batch config write, validated per key.",
  "guild.roles.list": "Minimal role rows for dropdowns.",
  "guild.channels.list": "Minimal channel rows for dropdowns.",
  "guild.setup.run": "One-shot setup wizard bootstrap.",
  "guild.settings.set": "General guild settings form.",
  "guild.permits.list": "List permits with assignments.",
  "guild.permits.create": "Create an enforced or custom permit.",
  "guild.permits.update": "Rename or re-scope a permit.",
  "guild.permits.delete": "Delete a permit.",
  "guild.permits.assign": "Grant a permit to a role or user.",
  "guild.permits.unassign": "Revoke a permit grant.",
  "guild.cases.list": "Paged moderation cases.",
  "guild.cases.revoke": "Revoke a case.",
  "guild.warnThresholds.list": "List warn-count escalation rules.",
  "guild.warnThresholds.set": "Upsert a rule; null action deletes it. mute/vcmute need a duration.",
  "guild.panic.get": "Read panic-mode state.",
  "guild.panic.set": "Lock down the guild, optionally narrowed to channels.",
  "guild.verificationPanel.get": "Read the verification panel binding.",
  "guild.verificationPanel.set": "Bind the verification panel.",
  "guild.verificationPanel.delete": "Remove the verification panel.",
  "guild.logClaims.list": "List channels pending as log destinations.",
  "guild.logClaims.issue": "Issue a one-time code to claim a log channel.",
  "guild.logClaims.dismiss": "Resolve a claim as confirmed or dismissed; audit-logged.",
  "guild.verificationWeb.complete": "Complete a web verification flow.",
  "guild.backups.list": "List guild backups (role/channel counts).",
  "guild.backups.restore": "Restore a guild backup.",
  "guild.tempvc.generators.list": "List temporary-voice generator channels.",
  "guild.tempvc.generators.set": "Upsert a generator; null name deletes it.",
  "guild.tempvc.records.list": "List temporary-voice records.",
  "guild.reactionroles.menus.list": "List role menus for a guild.",
  "guild.reactionroles.menus.set": "Create or update a role menu with its options.",
  "guild.reactionroles.menus.delete": "Delete a role menu.",
  "guild.audit.list": "Paged guild audit log.",
  "guild.history.list": "Paged config change history.",
  "guild.history.rollback": "Roll config back to a history entry.",
  "guild.overrides.list": "List per-channel/role/user config overrides.",
  "guild.overrides.set": "Upsert an override; null value deletes it.",
  "guild.blocklist.list": "Paged guild blocklist.",
  "guild.blocklist.add": "Block a user.",
  "guild.blocklist.remove": "Unblock a user.",
  "guild.modNotes.list": "Moderator notes for a user.",
  "guild.modNotes.add": "Add a moderator note.",
  "guild.modNotes.remove": "Remove a moderator note.",
  "guild.appeals.verify": "Verify an appeal link token.",
  "guild.appeals.submit": "Submit an appeal message.",
  "guild.appeals.list": "Paged appeals for reviewers.",
  "guild.appeals.review": "Approve, deny, blacklist-deny, or dismiss.",
  "guild.afk.list": "List AFK entries.",
  "guild.ignored.list": "List ignored channels.",
  "guild.ignored.add": "Ignore a channel; null targets the guild-wide row.",
  "guild.ignored.remove": "Un-ignore a channel.",
  "guild.moduleData.list": "Inspect stored module data.",
  "auth.whoami": "Returns { isBotOwner }; defers to the worker PermitResolver.",
  "system.dashboard.get": "System-panel overview.",
  "system.maintenance.set": "Toggle maintenance mode.",
  "system.module.toggle": "Globally toggle a module.",
  "system.module.clear": "Clear a module's global state.",
  "system.identity.set": "Set invite URL and support guild.",
  "system.audit.list": "Cross-guild audit log.",
  "system.blocklist.list": "Global blocklist.",
  "system.blocklist.add": "Add to the global blocklist.",
  "system.blocklist.remove": "Remove from the global blocklist.",
  "system.shards.get": "Shard telemetry: replicas, shard states, missing ids.",
};

async function generateRpcActions(): Promise<void> {
  const src = await fs.readFile(
    path.join(REPO_ROOT, "packages/contracts/src/rpc.ts"),
    "utf8",
  );
  const blockMatch = src.match(
    /export interface RpcRequestPayloads \{([\s\S]*?)\n\}/,
  );
  if (!blockMatch) {
    throw new Error("[generate-content] Could not find RpcRequestPayloads in packages/contracts/src/rpc.ts");
  }
  const entries: { name: string; payload: string }[] = [];
  for (const m of blockMatch[1]!.matchAll(/^\s*"([a-zA-Z.]+)":\s*(.+);\s*$/gm)) {
    entries.push({ name: m[1]!, payload: m[2]! });
  }
  if (entries.length === 0) {
    throw new Error("[generate-content] Parsed zero RPC actions out of RpcRequestPayloads — the regex likely no longer matches the file's shape.");
  }

  const problems: string[] = [];
  const actionNames = new Set(entries.map((e) => e.name));
  for (const name of actionNames) {
    if (!(name in rpcSummaries)) problems.push(`rpc.ts declares "${name}" with no docs summary`);
  }
  for (const name of Object.keys(rpcSummaries)) {
    if (!actionNames.has(name)) problems.push(`docs summary for "${name}" has no matching entry in RpcRequestPayloads`);
  }
  if (problems.length > 0) {
    throw new Error(`[generate-content] RPC reference drifted from source:\n  ${problems.join("\n  ")}`);
  }

  const rows = entries.map((e) => ({
    name: e.name,
    payload: e.payload === "never" ? "none" : e.payload,
    summary: rpcSummaries[e.name]!,
  }));

  await writeGenerated(
    "rpc-actions.ts",
    `export interface RpcActionRow {
  name: string;
  payload: string;
  summary: string;
}

export const rpcActions: RpcActionRow[] = ${JSON.stringify(rows, null, 2)};

export const rpcActionCount: number = rpcActions.length;
`,
  );
}

// --- 6. Commands ----------------------------------------------------------------

interface CommandEntry {
  module: string;
  name: string;
  description: string;
  requiredPermit: string | null;
  subcommands: string[];
}

/** Extracts the balanced `{ ... }` object literal that follows `@ApplyOptions<...>(`. */
function extractApplyOptionsBlocks(src: string): string[] {
  const blocks: string[] = [];
  const marker = "@ApplyOptions<";
  let searchFrom = 0;
  for (;;) {
    const markerIdx = src.indexOf(marker, searchFrom);
    if (markerIdx === -1) break;
    const openParen = src.indexOf("(", markerIdx);
    const openBrace = src.indexOf("{", openParen);
    if (openParen === -1 || openBrace === -1) break;
    let depth = 0;
    let i = openBrace;
    for (; i < src.length; i++) {
      if (src[i] === "{") depth++;
      else if (src[i] === "}") {
        depth--;
        if (depth === 0) break;
      }
    }
    blocks.push(src.slice(openBrace, i + 1));
    searchFrom = i + 1;
  }
  return blocks;
}

function firstMatch(block: string, re: RegExp): string | null {
  const m = block.match(re);
  return m ? m[1]! : null;
}

async function generateCommands(manifests: Manifest[]): Promise<void> {
  const byModule = new Map(manifests.map((m) => [m.name, m]));
  const commands: CommandEntry[] = [];

  for (const moduleName of MODULE_NAMES) {
    const dir = path.join(REPO_ROOT, "packages/core/src/modules", moduleName, "commands");
    let files: string[];
    try {
      files = (await fs.readdir(dir)).filter((f) => f.endsWith(".ts"));
    } catch {
      continue;
    }
    for (const file of files) {
      const src = await fs.readFile(path.join(dir, file), "utf8");
      for (const block of extractApplyOptionsBlocks(src)) {
        const name = firstMatch(block, /name:\s*"([^"]+)"/);
        const description = firstMatch(block, /description:\s*"((?:[^"\\]|\\.)*)"/);
        if (!name || !description) continue;
        const requiredPermit = firstMatch(block, /requiredPermit:\s*"([^"]+)"/);
        const subcommandsBlock = block.match(/subcommands:\s*\[([\s\S]*?)\]/);
        const subcommands = subcommandsBlock
          ? [...subcommandsBlock[1]!.matchAll(/name:\s*"([^"]+)"/g)].map((m) => m[1]!)
          : [];
        commands.push({
          module: moduleName,
          name,
          description: description.replace(/\\"/g, '"'),
          requiredPermit,
          subcommands,
        });
      }
    }
  }

  if (commands.length === 0) {
    throw new Error("[generate-content] Parsed zero commands out of packages/core/src/modules/*/commands — the extractor likely no longer matches the source shape.");
  }

  commands.sort((a, b) => a.module.localeCompare(b.module) || a.name.localeCompare(b.name));

  const groups = MODULE_NAMES.map((name) => {
    const manifest = byModule.get(name)!;
    return {
      module: name,
      displayName: manifest.displayName,
      emoji: manifest.emoji,
      commands: commands.filter((c) => c.module === name),
    };
  }).filter((g) => g.commands.length > 0);

  await writeGenerated(
    "commands.ts",
    `export interface CommandRow {
  module: string;
  name: string;
  description: string;
  requiredPermit: string | null;
  subcommands: string[];
}

export interface CommandGroup {
  module: string;
  displayName: string;
  emoji: string;
  commands: CommandRow[];
}

export const commandGroups: CommandGroup[] = ${JSON.stringify(groups, null, 2)};

export const commandCount: number = ${commands.length};
`,
  );
}

async function main() {
  const manifests = await loadManifests();
  await Promise.all([
    generateModules(manifests),
    generateDataPrivacy(manifests),
    generatePermits(),
    generateEnvVars(),
    generateRpcActions(),
    generateCommands(manifests),
  ]);
  console.log(`[generate-content] wrote generated docs data to ${path.relative(REPO_ROOT, OUT_DIR)}/`);
}

await main();
